---
dir_config:  # name of the directories
  root_dir: null
  raw_data_dir: 'raw'
  processed_data_dir: 'processed'
  logs: 'logs'
  results: 'results'
  utils: 'utils'
model_config:  # ML model training configuration
  config1:
    scaled_flag: True
    batch_size: 256
    n_epochs: 20
    lr: 0.001
  config2:
    scaled_flag: False
    batch_size: 128
    n_epochs: 10
    lr: 0.001
adv_config:  # Adversarial configuration
  goals: 'both'  # [normal, malicious or both]
  knowledge: 'test'  # [train or test]
  capability:  # common for lowprofool and deepfool
    batch_size: 64  # prefer a very small batch size
    cor_weights: False  # if correlation weights to be used instead of random forest weights
    perturb_threshold_features: 0.05
  lowprofool:
    max_iters: 2000  # total number of iterations
    alpha: 0.01  # step size
    lambda: 11.5  # trade-off factor
  deepfool:
    max_iters: 2000  # total number of iterations
    alpha: 0.001  # step size
    overshoot: 0.02
    epsilon: 0.00001
...