adv_config:
  capability:
    batch_size: 64
    cor_weights: false
    perturb_threshold_features: 0.02
  deepfool:
    alpha: 0.001
    epsilon: 1.0e-05
    max_iters: 2000
    overshoot: 0.02
  goals: both
  knowledge: test
  lowprofool:
    alpha: 0.01
    lambda: 4.5
    max_iters: 2000
dataset: CICIDS
dir_config:
  logs: /Users/sharma/PycharmProjects/Adversarial-Attacks-ML-based-IDS/logs
  processed_data_dir: /Users/sharma/PycharmProjects/Adversarial-Attacks-ML-based-IDS/data/CICIDS/processed
  raw_data_dir: /Users/sharma/PycharmProjects/Adversarial-Attacks-ML-based-IDS/data/CICIDS/raw
  results: /Users/sharma/PycharmProjects/Adversarial-Attacks-ML-based-IDS/results/CICIDS
  root_dir: /Users/sharma/PycharmProjects/Adversarial-Attacks-ML-based-IDS
  utils: /Users/sharma/PycharmProjects/Adversarial-Attacks-ML-based-IDS/utils/CICIDS
model_config:
  batch_size: 256
  lr: 0.001
  n_epochs: 20
  scaled_flag: true
preprocess_data: false
sample_data: false