CICDDoS:
  functional_features:
  - SourcePort
  - DestinationPort
  - Protocol
  non_perturbed_features:
  - SubflowFwdBytes
  - PacketLengthVariance
  - FlowDuration
  - BwdPacketLengthMin
  - act_data_pkt_fwd
  - TotalBackwardPackets
  - Init_Win_bytes_backward
  - Init_Win_bytes_forward
  - BwdIATTotal
  - FlowIATMean
  - TotalLengthofFwdPackets
  - SubflowBwdPackets
  - BwdHeaderLength
  - ActiveMin
CICIDS:
  binary_features:
  - FwdPSHFlags
  - FwdURGFlags
  - FINFlagCount
  - SYNFlagCount
  - RSTFlagCount
  - PSHFlagCount
  - ACKFlagCount
  - URGFlagCount
  - CWEFlagCount
  - ECEFlagCount
  functional_features: null
  non_perturbed_features:
  - BwdPacketLengthMax
  - FwdIATStd
  - FwdPacketLengthStd
  - Init_Win_bytes_forward
  - TotalLengthofFwdPackets
  - BwdPacketLengthMin
  - AveragePacketSize
  - IdleMean
  - FwdPacketLengthMax
  - FlowIATMax
  - PacketLengthMean
  - act_data_pkt_fwd
  - TotalFwdPackets
  - SubflowFwdBytes
  - Init_Win_bytes_backward
  - PacketLengthStd
  - BwdPacketLengthStd
  perturbed_features:
  - FlowIATMin
  - BwdIATTotal
  - PacketLengthVariance
  - BwdIATMin
  - FlowDuration
  - BwdIATStd
  - SubflowBwdBytes
  - IdleStd
  - ActiveMean
  - ActiveMax
  - BwdIATMax
  - FwdIATMean
  - ActiveStd
  - BwdIATMean
  - FwdHeaderLength
  - FwdIATMax
  - FlowIATMean
  - FwdIATTotal
  - FwdIATMin
  - Down/UpRatio
  - TotalBackwardPackets
  - SubflowFwdPackets
  - FlowIATStd
  - TotalLengthofBwdPackets
  - ActiveMin
  - IdleMin
  - SubflowBwdPackets
  - min_seg_size_forward
  - BwdHeaderLength
  - IdleMax
  - FwdPacketLengthMin
NSL-KDD:
  functional_features:
  - duration
  - protocol_type
  - service
  - flag
  - hot
  - srv_rerror_rate
  - num_root
  non_perturbed_features:
  - duration
  - dst_host_same_srv_rate
  - dst_bytes
  - src_bytes
  - num_file_creations
  - su_attempted
  - num_shells