CICDDoS:
  binary_features:
  - FwdPSHFlags
  - SYNFlagCount
  - RSTFlagCount
  - ACKFlagCount
  - URGFlagCount
  - CWEFlagCount
  - Inbound
  functional_features:
  - SourcePort
  - DestinationPort
  - Protocol
  non_perturbed_features:
  - TotalLengthofFwdPackets
  - PacketLengthMean
  - FwdPacketLengthMin
  - Init_Win_bytes_forward
  - SubflowFwdBytes
  - AveragePacketSize
  - FwdPacketLengthMax
  perturbed_features:
  - BwdIATStd
  - IdleStd
  - BwdIATMin
  - min_seg_size_forward
  - BwdPacketLengthMin
  - BwdIATMean
  - PacketLengthStd
  - SubflowBwdPackets
  - TotalFwdPackets
  - IdleMin
  - FlowDuration
  - BwdHeaderLength
  - IdleMax
  - BwdPacketLengthStd
  - TotalLengthofBwdPackets
  - FlowIATStd
  - Down/UpRatio
  - FlowIATMean
  - FwdIATMin
  - SubflowBwdBytes
  - act_data_pkt_fwd
  - ActiveStd
  - FlowIATMax
  - FwdHeaderLength
  - ActiveMean
  - FwdIATMean
  - FwdPacketLengthStd
  - PacketLengthVariance
  - ActiveMin
  - FwdIATTotal
  - ActiveMax
  - FlowIATMin
  - BwdIATMax
  - SubflowFwdPackets
  - IdleMean
  - BwdIATTotal
  - Init_Win_bytes_backward
  - FwdIATStd
  - TotalBackwardPackets
  - FwdIATMax
  - BwdPacketLengthMax
CICIDS:
  functional_features: null
  non_perturbed_features: null
NSL-KDD:
  functional_features:
  - duration
  - protocol_type
  - service
  - flag
  non_perturbed_features:
  - duration
