CICDDoS:
  binary_features:
  - FwdPSHFlags
  - SYNFlagCount
  - RSTFlagCount
  - ACKFlagCount
  - URGFlagCount
  - CWEFlagCount
  - Inbound
  functional_features:
  - SourcePort
  - DestinationPort
  - Protocol
  non_perturbed_features:
  - TotalLengthofFwdPackets
  - AveragePacketSize
  - PacketLengthMean
  - FwdPacketLengthMax
  - FwdPacketLengthMin
  perturbed_features:
  - FwdIATStd
  - IdleMean
  - SubflowFwdPackets
  - IdleMax
  - FwdIATTotal
  - Down/UpRatio
  - FlowIATStd
  - SubflowBwdPackets
  - Init_Win_bytes_backward
  - act_data_pkt_fwd
  - SubflowFwdBytes
  - BwdPacketLengthMin
  - BwdIATMax
  - ActiveMean
  - BwdHeaderLength
  - FlowIATMax
  - BwdIATMin
  - SubflowBwdBytes
  - IdleStd
  - FwdPacketLengthStd
  - FwdIATMean
  - PacketLengthVariance
  - Init_Win_bytes_forward
  - BwdIATMean
  - PacketLengthStd
  - BwdIATStd
  - FlowIATMean
  - min_seg_size_forward
  - FlowDuration
  - TotalFwdPackets
  - BwdPacketLengthMax
  - FwdHeaderLength
  - FwdIATMax
  - ActiveMax
  - IdleMin
  - TotalBackwardPackets
  - FlowIATMin
  - BwdPacketLengthStd
  - ActiveMin
  - TotalLengthofBwdPackets
  - FwdIATMin
  - BwdIATTotal
  - ActiveStd
CICIDS:
  functional_features: null
  non_perturbed_features: null
NSL-KDD:
  functional_features:
  - duration
  - protocol_type
  - service
  - flag
  - hot
  - srv_rerror_rate
  non_perturbed_features:
  - duration
